# Default values for golang-http.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

priorityClassName: ""

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
#  - key: "key"
#    operator: "Equal|Exists"
#    value: "value"
#    effect: "NoSchedule|PreferNoSchedule|NoExecute"

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

podAnnotations: {}

podLabels: {}

image:
  repository: 337222843631.dkr.ecr.ap-southeast-1.amazonaws.com/viddsee-bot/golang-http
  tag: 0.0.16
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

ingress:
  ## If true, Ingress will be created.
  ##
  enabled: true

  # Used to create Ingress record (should used with ServiceType: ClusterIP).
  hosts:
    - chart.local

  ## Ingress annotations
  ##
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

  ## Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  tls:
    - secretName: chart-tls
      hosts:
        - chart.local
